name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.4
    - name: Setup .NET 7 SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Publish Script
      run: cd scripts && ./publish.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DayZLauncher-UnixPatcher
        path: "./release"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DayZLauncher-UnixPatcher-Musl
        path: "./release-musl"