# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.4
    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Publish Script
      run: cd scripts && ./publish.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DayZLauncher-UnixPatcher
        path: "./unixpatcher.tar.xz"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DayZLauncher-UnixPatcher-Musl
        path: "./unixpatcher-musl.tar.xz"